nodes:
  - path: /hardware/autonomous_available
    type: and
    list:
      - { type: link, link: /hardware/emergency_stop }
      - { type: link, link: /hardware/pull_over }
      - { type: link, link: /hardware/comfortable_stop }

  - path: /hardware/pull_over_available
    type: and
    list:
      - { type: link, link: /hardware/emergency_stop }
      - { type: link, link: /hardware/comfortable_stop }

  - path: /hardware/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /hardware/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /hardware/emergency_stop
    type: and
    list:
      - { type: link, link: /hardware/cpu/002-usage-error }
      - { type: link, link: /hardware/cpu/004-throttling-error }
      - { type: link, link: /hardware/hdd/001-temperature-error }
      - { type: link, link: /hardware/hdd/003-connection-error }
      - { type: link, link: /hardware/hdd/006-soft_error-error }
      - { type: link, link: /hardware/hdd/007-load-error }
      - { type: link, link: /hardware/memory/001-usage-error }
      - { type: link, link: /hardware/memory/002-ecc-error }
      - { type: link, link: /hardware/network/003-crc-error }
      - { type: link, link: /hardware/network/004-packet_reassembles-error }
      - { type: link, link: /hardware/gpu/001-temperature-error }
      - { type: link, link: /hardware/gpu/002-usage-error }
      - { type: link, link: /hardware/gpu/003-memory-error }
      - { type: link, link: /hardware/gpu/004-throttling-error }
      - { type: link, link: /hardware/gpu/005-frequency-error }

  - path: /hardware/pull_over
    type: and
    list:
      - { type: link, link: /hardware/hdd/002-usage-error }
      - { type: link, link: /hardware/mot/001-connection }
      - { type: link, link: /hardware/signage/001-connection }
      - { type: link, link: /hardware/voice/001-connection }

  - path: /hardware/comfortable_stop
    type: and

  - path: /hardware/none
    type: and
    list:
      - { type: link, link: /hardware/cpu/001-temperature }
      - { type: link, link: /hardware/cpu/003-load_average }
      - { type: link, link: /hardware/cpu/005-frequency }
      - { type: link, link: /hardware/hdd/004-total_written }
      - { type: link, link: /hardware/hdd/005-warranty_period }
      - { type: link, link: /hardware/network/001-usage }
      - { type: link, link: /hardware/network/002-traffic }
      - { type: link, link: /hardware/ntp/001-sync }
      - { type: link, link: /hardware/process/001-summary }
      - { type: link, link: /hardware/process/002-load }
      - { type: link, link: /hardware/process/003-memory }
      - { type: link, link: /hardware/bios/001-battery }

  # Intermediate paths
  - path: /hardware/cpu/002-usage-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/cpu/002-usage }

  - path: /hardware/cpu/004-throttling-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/cpu/004-throttling }

  - path: /hardware/hdd/001-temperature-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/hdd/001-temperature }

  - path: /hardware/hdd/002-usage-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/hdd/002-usage }

  - path: /hardware/hdd/003-connection-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/hdd/003-connection }

  - path: /hardware/hdd/006-soft_error-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/hdd/006-soft_error }

  - path: /hardware/hdd/007-load-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/hdd/007-load }

  - path: /hardware/memory/001-usage-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/memory/001-usage }

  - path: /hardware/memory/002-ecc-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/memory/002-ecc }

  - path: /hardware/network/003-crc-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/network/003-crc }

  - path: /hardware/gpu/001-temperature-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/gpu/001-temperature }

  - path: /hardware/gpu/002-usage-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/gpu/002-usage }

  - path: /hardware/gpu/003-memory-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/gpu/003-memory }

  - path: /hardware/gpu/004-throttling-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/gpu/004-throttling }

  - path: /hardware/gpu/005-frequency-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/gpu/005-frequency }

  - path: /hardware/network/004-packet_reassembles-error
    type: warn-to-ok
    list:
      - { type: link, link: /hardware/network/004-packet_reassembles }

  - path: /hardware/hdd/007-load
    type: and
    list:
      - { type: link, link: /hardware/hdd/007-load/read_rate }
      - { type: link, link: /hardware/hdd/007-load/read_iops }
      - { type: link, link: /hardware/hdd/007-load/write_rate }
      - { type: link, link: /hardware/hdd/007-load/write_iops }

  - path: /hardware/process/002-load
    type: and
    list:
      - { type: link, link: /hardware/process/002-load/proc-0 }
      - { type: link, link: /hardware/process/002-load/proc-1 }
      - { type: link, link: /hardware/process/002-load/proc-2 }
      - { type: link, link: /hardware/process/002-load/proc-3 }
      - { type: link, link: /hardware/process/002-load/proc-4 }

  - path: /hardware/process/003-memory
    type: and
    list:
      - { type: link, link: /hardware/process/003-memory/proc-0 }
      - { type: link, link: /hardware/process/003-memory/proc-1 }
      - { type: link, link: /hardware/process/003-memory/proc-2 }
      - { type: link, link: /hardware/process/003-memory/proc-3 }
      - { type: link, link: /hardware/process/003-memory/proc-4 }

  # Diagnostics paths
  - path: /hardware/cpu/001-temperature
    diag: "cpu_monitor: CPU Temperature"
    type: diag
    timeout: 3.0
  - path: /hardware/cpu/002-usage
    diag: "cpu_monitor: CPU Usage"
    type: diag
    timeout: 3.0
  - path: /hardware/cpu/003-load_average
    diag: "cpu_monitor: CPU Load Average"
    type: diag
    timeout: 3.0
  - path: /hardware/cpu/004-throttling
    diag: "cpu_monitor: CPU Thermal Throttling"
    type: diag
    timeout: 3.0
  - path: /hardware/cpu/005-frequency
    diag: "cpu_monitor: CPU Frequency"
    type: diag
    timeout: 3.0

  - path: /hardware/hdd/001-temperature
    diag: "hdd_monitor: HDD Temperature"
    type: diag
    timeout: 3.0
  - path: /hardware/hdd/002-usage
    diag: "hdd_monitor: HDD Usage"
    type: diag
    timeout: 3.0
  - path: /hardware/hdd/003-connection
    diag: "hdd_monitor: HDD Connection"
    type: diag
    timeout: 3.0
  - path: /hardware/hdd/004-total_written
    diag: "hdd_monitor: HDD TotalDataWritten"
    type: diag
    timeout: 3.0
  - path: /hardware/hdd/005-warranty_period
    diag: "hdd_monitor: HDD PowerOnHours"
    type: diag
    timeout: 3.0
  - path: /hardware/hdd/006-soft_error
    diag: "hdd_monitor: HDD RecoveredError"
    type: diag
    timeout: 3.0
  - path: /hardware/hdd/007-load/read_rate
    diag: "hdd_monitor: HDD ReadDataRate"
    type: diag
    timeout: 3.0
  - path: /hardware/hdd/007-load/write_rate
    diag: "hdd_monitor: HDD WriteDataRate"
    type: diag
    timeout: 3.0
  - path: /hardware/hdd/007-load/read_iops
    diag: "hdd_monitor: HDD ReadIOPS"
    type: diag
    timeout: 3.0
  - path: /hardware/hdd/007-load/write_iops
    diag: "hdd_monitor: HDD WriteIOPS"
    type: diag
    timeout: 3.0

  - path: /hardware/memory/001-usage
    diag: "mem_monitor: Memory Usage"
    type: diag
    timeout: 3.0
  - path: /hardware/memory/002-ecc
    diag: "mem_monitor: Memory ECC"
    type: diag
    timeout: 3.0

  - path: /hardware/network/001-usage
    diag: "net_monitor: Network Usage"
    type: diag
    timeout: 3.0
  - path: /hardware/network/002-traffic
    diag: "net_monitor: Network Traffic"
    type: diag
    timeout: 3.0
  - path: /hardware/network/003-crc
    diag: "net_monitor: Network CRC Error"
    type: diag
    timeout: 3.0
  - path: /hardware/network/004-packet_reassembles
    diag: "net_monitor: IP Packet Reassembles Failed"
    type: diag
    timeout: 3.0

  - path: /hardware/ntp/001-sync
    diag: "ntp_monitor: NTP Offset"
    type: diag
    timeout: 10.0

  - path: /hardware/process/001-summary
    diag: "process_monitor: Tasks Summary"
    type: diag
    timeout: 3.0
  - path: /hardware/process/002-load/proc-0
    diag: "process_monitor: High-load Proc[0]"
    type: diag
    timeout: 3.0
  - path: /hardware/process/002-load/proc-1
    diag: "process_monitor: High-load Proc[1]"
    type: diag
    timeout: 3.0
  - path: /hardware/process/002-load/proc-2
    diag: "process_monitor: High-load Proc[2]"
    type: diag
    timeout: 3.0
  - path: /hardware/process/002-load/proc-3
    diag: "process_monitor: High-load Proc[3]"
    type: diag
    timeout: 3.0
  - path: /hardware/process/002-load/proc-4
    diag: "process_monitor: High-load Proc[4]"
    type: diag
    timeout: 3.0
  - path: /hardware/process/003-memory/proc-0
    diag: "process_monitor: High-mem Proc[0]"
    type: diag
    timeout: 3.0
  - path: /hardware/process/003-memory/proc-1
    diag: "process_monitor: High-mem Proc[1]"
    type: diag
    timeout: 3.0
  - path: /hardware/process/003-memory/proc-2
    diag: "process_monitor: High-mem Proc[2]"
    type: diag
    timeout: 3.0
  - path: /hardware/process/003-memory/proc-3
    diag: "process_monitor: High-mem Proc[3]"
    type: diag
    timeout: 3.0
  - path: /hardware/process/003-memory/proc-4
    diag: "process_monitor: High-mem Proc[4]"
    type: diag
    timeout: 3.0

  - path: /hardware/gpu/001-temperature
    diag: "gpu_monitor: GPU Temperature"
    type: diag
    timeout: 3.0
  - path: /hardware/gpu/002-usage
    diag: "gpu_monitor: GPU Usage"
    type: diag
    timeout: 3.0
  - path: /hardware/gpu/003-memory
    diag: "gpu_monitor: GPU Memory Usage"
    type: diag
    timeout: 3.0
  - path: /hardware/gpu/004-throttling
    diag: "gpu_monitor: GPU Thermal Throttling"
    type: diag
    timeout: 3.0
  - path: /hardware/gpu/005-frequency
    diag: "gpu_monitor: GPU Frequency"
    type: diag
    timeout: 3.0

  - path: /hardware/bios/001-battery
    diag: "voltage_monitor: CMOS Battery Status"
    type: diag
    timeout: 3.0

  # We assume these diagnostics become only OK or STALE
  - path: /hardware/mot/001-connection
    diag: "mot: /system/mot_connection : mot heartbeat"
    type: diag
    timeout: 5.0

  - path: /hardware/signage/001-connection
    diag: "signage: /system/signage_connection : signage heartbeat"
    type: diag
    timeout: 5.0

  - path: /hardware/voice/001-connection
    diag: "vehicle_voice_alert_system: /system/voice_alert_system_connection : voirce alert system heartbeat"
    type: diag
    timeout: 5.0
