nodes:
  - path: /localization/autonomous_available
    type: and
    list:
      - { type: link, link: /localization/emergency_stop }
      - { type: link, link: /localization/pull_over }
      - { type: link, link: /localization/comfortable_stop }

  - path: /localization/pull_over_available
    type: and
    list:
      - { type: link, link: /localization/emergency_stop }
      - { type: link, link: /localization/comfortable_stop }

  - path: /localization/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /localization/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /localization/emergency_stop
    type: and
    list:
      - { type: link, link: /localization/001-topic_status/initialpose-error }
      - { type: link, link: /localization/001-topic_status/pose_twist_fusion_filter-error }
      - { type: link, link: /localization/002-tf-error }
      - { type: link, link: /localization/003-matching_score-error }
      - { type: link, link: /localization/004-accuracy-error }
      - { type: link, link: /localization/005-accuracy_lateral-error }

  - path: /localization/comfortable_stop
    type: and

  - path: /localization/pull_over
    type: and

  - path: /localization/none
    type: and

  # Intermediate paths
  - path: /localization/001-topic_status/initialpose-error
    type: warn-to-ok
    list:
      - { type: link, link: /localization/001-topic_status/initialpose }

  - path: /localization/001-topic_status/pose_twist_fusion_filter-error
    type: warn-to-ok
    list:
      - { type: link, link: /localization/001-topic_status/pose_twist_fusion_filter }

  - path: /localization/002-tf-error
    type: warn-to-ok
    list:
      - { type: link, link: /localization/002-tf }

  - path: /localization/003-matching_score-error
    type: warn-to-ok
    list:
      - { type: link, link: /localization/003-matching_score }

  - path: /localization/004-accuracy-error
    type: warn-to-ok
    list:
      - { type: link, link: /localization/004-accuracy }

  - path: /localization/005-accuracy_lateral-error
    type: warn-to-ok
    list:
      - { type: link, link: /localization/005-accuracy_lateral }

  # Diagnostics paths
  - path: /localization/001-topic_status/initialpose
    diag: "topic_state_monitor_initialpose3d: localization_topic_status"
    type: diag

  - path: /localization/001-topic_status/pose_twist_fusion_filter
    diag: "topic_state_monitor_pose_twist_fusion_filter_pose: localization_topic_status"
    type: diag

  - path: /localization/002-tf
    diag: "topic_state_monitor_transform_map_to_base_link: localization_topic_status"
    type: diag

  - path: /localization/003-matching_score
    diag: ndt_scan_matcher
    type: diag

  - path: /localization/004-accuracy
    diag: "localization_error_monitor: localization_accuracy"
    type: diag

  - path: /localization/005-accuracy_lateral
    diag: "localization_error_monitor: localization_accuracy_lateral_direction"
    type: diag
