nodes:
  - path: /others/autonomous_available
    type: and
    list:
      - { type: link, link: /others/emergency_stop }
      - { type: link, link: /others/pull_over }
      - { type: link, link: /others/comfortable_stop }

  - path: /others/pull_over_available
    type: and
    list:
      - { type: link, link: /others/emergency_stop }
      - { type: link, link: /others/comfortable_stop }

  - path: /others/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /others/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /others/emergency_stop
    type: and
    list:
      - { type: link, link: /others/002-blockage_validation-error }
      - { type: link, link: /others/004-concat_status }
      - { type: link, link: /others/005-visibility_validation-error }

  - path: /others/comfortable_stop
    type: and
    list:
      - { type: link, link: /others/010-emergency_vehicle-error }

  - path: /others/pull_over
    type: and
    list:
      - { type: link, link: /others/011-daytime_monitor }

  - path: /others/none
    type: and

  # Intermediate paths
  - path: /others/002-blockage_validation
    type: and
    list:
      - { type: link, link: /others/002-blockage_validation/front_lower }
      - { type: link, link: /others/002-blockage_validation/front_upper }
      - { type: link, link: /others/002-blockage_validation/left_lower }
      - { type: link, link: /others/002-blockage_validation/left_upper }
      - { type: link, link: /others/002-blockage_validation/right_lower }
      - { type: link, link: /others/002-blockage_validation/right_upper }
      - { type: link, link: /others/002-blockage_validation/rear_lower }
      - { type: link, link: /others/002-blockage_validation/rear_upper }

  - path: /others/005-visibility_validation
    type: and
    list:
      - { type: link, link: /others/005-visibility_validation/front_lower }

  - path: /others/002-blockage_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /others/002-blockage_validation }

  - path: /others/005-visibility_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /others/005-visibility_validation }

  - path: /others/010-emergency_vehicle-error
    type: warn-to-ok
    list:
      - { type: link, link: /others/010-emergency_vehicle }

  # Diagnostics paths
  - path: /others/002-blockage_validation/front_lower
    diag: "blockage_return_diag: /sensing/lidar/front_lower: blockage_validation"
    type: diag
    timeout: 1.0
  - path: /others/002-blockage_validation/front_upper
    diag: "blockage_return_diag: /sensing/lidar/front_upper: blockage_validation"
    type: diag
    timeout: 1.0
  - path: /others/002-blockage_validation/left_lower
    diag: "blockage_return_diag: /sensing/lidar/left_lower: blockage_validation"
    type: diag
    timeout: 1.0
  - path: /others/002-blockage_validation/left_upper
    diag: "blockage_return_diag: /sensing/lidar/left_upper: blockage_validation"
    type: diag
    timeout: 1.0
  - path: /others/002-blockage_validation/right_lower
    diag: "blockage_return_diag: /sensing/lidar/right_lower: blockage_validation"
    type: diag
    timeout: 1.0
  - path: /others/002-blockage_validation/right_upper
    diag: "blockage_return_diag: /sensing/lidar/right_upper: blockage_validation"
    type: diag
    timeout: 1.0
  - path: /others/002-blockage_validation/rear_lower
    diag: "blockage_return_diag: /sensing/lidar/rear_lower: blockage_validation"
    type: diag
    timeout: 1.0
  - path: /others/002-blockage_validation/rear_upper
    diag: "blockage_return_diag: /sensing/lidar/rear_upper: blockage_validation"
    type: diag
    timeout: 1.0

  - path: /others/004-concat_status
    diag: "concatenate_data: concat_status"
    type: diag
    timeout: 1.0

  - path: /others/005-visibility_validation/front_lower
    diag: "dual_return_filter: /sensing/lidar/front_lower: visibility_validation"
    type: diag
    timeout: 1.0

  - path: /others/010-emergency_vehicle
    diag: "emergency_vehicle_detector: emergency_vehicle"
    type: diag
    timeout: 1.0

  - path: /others/011-daytime_monitor
    diag: "daytime_monitor: daytime_status"
    type: diag
    timeout: 1.0
