nodes:
  - path: /planning/autonomous_available
    type: and
    list:
      - { type: link, link: /planning/emergency_stop }
      - { type: link, link: /planning/pull_over }
      - { type: link, link: /planning/comfortable_stop }

  - path: /planning/pull_over_available
    type: and
    list:
      - { type: link, link: /planning/emergency_stop }
      - { type: link, link: /planning/comfortable_stop }

  - path: /planning/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /planning/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /planning/emergency_stop
    type: and
    list:
      - { type: link, link: /planning/001-topic_status/route-error }
      - { type: link, link: /planning/001-topic_status/trajectory-error }
      - { type: link, link: /planning/003-trajectory_finite_validation-error }
      - { type: link, link: /planning/004-trajectory_interval_validation-error }
      - { type: link, link: /planning/005-trajectory_curvature_validation-error }
      - { type: link, link: /planning/006-trajectory_relative_angle_validation-error }
      - { type: link, link: /planning/007-trajectory_lateral_acceleration_validation-error }
      - { type: link, link: /planning/008-trajectory_acceleration_validation-error }
      - { type: link, link: /planning/009-trajectory_deceleration_validation-error }
      - { type: link, link: /planning/010-trajectory_steering_validation-error }
      - { type: link, link: /planning/011-trajectory_steering_rate_validation-error }
      - { type: link, link: /planning/012-trajectory_velocity_deviation_validation-error }
      - { type: link, link: /planning/013-collision_checker-error }

  - path: /planning/comfortable_stop
    type: and

  - path: /planning/pull_over
    type: and

  - path: /planning/none
    type: and

  # Intermediate paths
  - path: /planning/001-topic_status/route-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/001-topic_status/route }

  - path: /planning/001-topic_status/trajectory-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/001-topic_status/trajectory }

  - path: /planning/003-trajectory_finite_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/003-trajectory_finite_validation }

  - path: /planning/004-trajectory_interval_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/004-trajectory_interval_validation }

  - path: /planning/005-trajectory_curvature_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/005-trajectory_curvature_validation }

  - path: /planning/006-trajectory_relative_angle_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/006-trajectory_relative_angle_validation }

  - path: /planning/007-trajectory_lateral_acceleration_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/007-trajectory_lateral_acceleration_validation }

  - path: /planning/008-trajectory_acceleration_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/008-trajectory_acceleration_validation }

  - path: /planning/009-trajectory_deceleration_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/009-trajectory_deceleration_validation }

  - path: /planning/010-trajectory_steering_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/010-trajectory_steering_validation }

  - path: /planning/011-trajectory_steering_rate_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/011-trajectory_steering_rate_validation }

  - path: /planning/012-trajectory_velocity_deviation_validation-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/012-trajectory_velocity_deviation_validation }

  - path: /planning/013-collision_checker-error
    type: warn-to-ok
    list:
      - { type: link, link: /planning/013-collision_checker }

  # Diagnostics paths
  - path: /planning/001-topic_status/route
    diag: "topic_state_monitor_mission_planning_route: planning_topic_status"
    type: diag
    timeout: 1.0

  - path: /planning/001-topic_status/trajectory
    diag: "topic_state_monitor_scenario_planning_trajectory: planning_topic_status"
    type: diag
    timeout: 1.0

  # Not implemented
  # - path: /planning/002-trajectory_size_validation
  #   diag: "planning_validator: trajectory_validation_size"
  #   type: diag

  - path: /planning/003-trajectory_finite_validation
    diag: "planning_validator: trajectory_validation_finite"
    type: diag
    timeout: 1.0

  - path: /planning/004-trajectory_interval_validation
    diag: "planning_validator: trajectory_validation_interval"
    type: diag
    timeout: 1.0

  - path: /planning/005-trajectory_curvature_validation
    diag: "planning_validator: trajectory_validation_curvature"
    type: diag
    timeout: 1.0

  - path: /planning/006-trajectory_relative_angle_validation
    diag: "planning_validator: trajectory_validation_relative_angle"
    type: diag
    timeout: 1.0

  - path: /planning/007-trajectory_lateral_acceleration_validation
    diag: "planning_validator: trajectory_validation_lateral_acceleration"
    type: diag
    timeout: 1.0

  - path: /planning/008-trajectory_acceleration_validation
    diag: "planning_validator: trajectory_validation_acceleration"
    type: diag
    timeout: 1.0

  - path: /planning/009-trajectory_deceleration_validation
    diag: "planning_validator: trajectory_validation_deceleration"
    type: diag
    timeout: 1.0

  - path: /planning/010-trajectory_steering_validation
    diag: "planning_validator: trajectory_validation_steering"
    type: diag
    timeout: 1.0

  - path: /planning/011-trajectory_steering_rate_validation
    diag: "planning_validator: trajectory_validation_steering_rate"
    type: diag
    timeout: 1.0

  - path: /planning/012-trajectory_velocity_deviation_validation
    diag: "planning_validator: trajectory_validation_velocity_deviation"
    type: diag
    timeout: 1.0

  - path: /planning/013-collision_checker
    diag: "collision_checker: collision_check"
    type: diag
    timeout: 1.0
