nodes:
  - path: /sensing/autonomous_available
    type: and
    list:
      - { type: link, link: /sensing/emergency_stop }
      - { type: link, link: /sensing/pull_over }
      - { type: link, link: /sensing/comfortable_stop }

  - path: /sensing/pull_over_available
    type: and
    list:
      - { type: link, link: /sensing/emergency_stop }
      - { type: link, link: /sensing/comfortable_stop }

  - path: /sensing/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /sensing/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /sensing/emergency_stop
    type: and
    list:
      - { type: link, link: /sensing/imu/001-monitor-error }
      - { type: link, link: /sensing/imu/002-connection }
      - { type: link, link: /sensing/lidar/pndr/001-connection }
      - { type: link, link: /sensing/lidar/pndr/002-temperature-error }
      - { type: link, link: /sensing/lidar/pndr/003-ptp }
      - { type: link, link: /sensing/camera/001-connection }
      - { type: link, link: /sensing/radar/001-connection }

  - path: /sensing/pull_over
    type: and
    list:
      - { type: link, link: /sensing/lidar/pndr/002-temperature }
      - { type: link, link: /sensing/gnss/001-connection-error }

  - path: /sensing/comfortable_stop
    type: and

  - path: /sensing/none
    type: and
    list:
      - { type: link, link: /sensing/imu/003-gyro_bias }
      - { type: link, link: /sensing/gnss/002-quality }

  # Intermediate paths
  - path: /sensing/lidar/pndr/002-temperature-error
    type: warn-to-ok
    list:
      - { type: link, link: /sensing/lidar/pndr/002-temperature }

  - path: /sensing/imu/001-monitor-error
    type: warn-to-ok
    list:
      - { type: link, link: /sensing/imu/001-monitor }

  - path: /sensing/gnss/001-connection-error
    type: warn-to-ok
    list:
      - { type: link, link: /sensing/gnss/001-connection }

  - path: /sensing/lidar/pndr/001-connection
    type: and
    list:
      - { type: link, link: /sensing/lidar/front_lower/connection }
      - { type: link, link: /sensing/lidar/front_upper/connection }
      - { type: link, link: /sensing/lidar/left_lower/connection }
      - { type: link, link: /sensing/lidar/left_upper/connection }
      - { type: link, link: /sensing/lidar/right_lower/connection }
      - { type: link, link: /sensing/lidar/right_upper/connection }
      - { type: link, link: /sensing/lidar/rear_lower/connection }
      - { type: link, link: /sensing/lidar/rear_upper/connection }

  - path: /sensing/lidar/pndr/002-temperature
    type: and
    list:
      - { type: link, link: /sensing/lidar/front_lower/temperature }
      - { type: link, link: /sensing/lidar/front_upper/temperature }
      - { type: link, link: /sensing/lidar/left_lower/temperature }
      - { type: link, link: /sensing/lidar/left_upper/temperature }
      - { type: link, link: /sensing/lidar/right_lower/temperature }
      - { type: link, link: /sensing/lidar/right_upper/temperature }
      - { type: link, link: /sensing/lidar/rear_lower/temperature }
      - { type: link, link: /sensing/lidar/rear_upper/temperature }

  - path: /sensing/lidar/pndr/003-ptp
    type: and
    list:
      - { type: link, link: /sensing/lidar/front_lower/ptp }
      - { type: link, link: /sensing/lidar/front_upper/ptp }
      - { type: link, link: /sensing/lidar/left_lower/ptp }
      - { type: link, link: /sensing/lidar/left_upper/ptp }
      - { type: link, link: /sensing/lidar/right_lower/ptp }
      - { type: link, link: /sensing/lidar/right_upper/ptp }
      - { type: link, link: /sensing/lidar/rear_lower/ptp }
      - { type: link, link: /sensing/lidar/rear_upper/ptp }

  - path: /sensing/camera/001-connection
    type: and
    list:
      - { type: link, link: /sensing/camera/0/connection }
      - { type: link, link: /sensing/camera/1/connection }
      - { type: link, link: /sensing/camera/2/connection }
      - { type: link, link: /sensing/camera/3/connection }
      - { type: link, link: /sensing/camera/4/connection }
      - { type: link, link: /sensing/camera/5/connection }

  - path: /sensing/radar/001-connection
    type: and
    list:
      - { type: link, link: /sensing/radar/front_center/connection }
      - { type: link, link: /sensing/radar/front_left/connection }
      - { type: link, link: /sensing/radar/front_right/connection }
      - { type: link, link: /sensing/radar/rear_center/connection }
      - { type: link, link: /sensing/radar/rear_left/connection }
      - { type: link, link: /sensing/radar/rear_right/connection }

  # Diagnostics paths
  - path: /sensing/imu/001-monitor
    diag: "imu_monitor: yaw_rate_status"
    type: diag
    timeout: 5.0
  - path: /sensing/imu/002-connection
    diag: "topic_state_monitor_imu_data: imu_topic_status"
    type: diag
    timeout: 1.0
  - path: /sensing/imu/003-gyro_bias
    diag: "gyro_bias_estimator: gyro_bias_validator"
    type: diag
    timeout: 1.0

  - path: /sensing/gnss/001-connection
    diag: "topic_state_monitor_gnss_pose: gnss_topic_status"
    type: diag
    timeout: 5.0
  - path: /sensing/gnss/002-quality
    diag: "septentrio_driver: Quality indicators"
    type: diag
    timeout: 5.0

  - path: /sensing/lidar/front_lower/connection
    diag: "pandar_monitor: /sensing/lidar/front_lower: pandar_connection"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/front_lower/ptp
    diag: "pandar_monitor: /sensing/lidar/front_lower: pandar_ptp"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/front_lower/temperature
    diag: "pandar_monitor: /sensing/lidar/front_lower: pandar_temperature"
    type: diag
    timeout: 5.0

  - path: /sensing/lidar/front_upper/connection
    diag: "pandar_monitor: /sensing/lidar/front_upper: pandar_connection"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/front_upper/ptp
    diag: "pandar_monitor: /sensing/lidar/front_upper: pandar_ptp"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/front_upper/temperature
    diag: "pandar_monitor: /sensing/lidar/front_upper: pandar_temperature"
    type: diag
    timeout: 5.0

  - path: /sensing/lidar/left_lower/connection
    diag: "pandar_monitor: /sensing/lidar/left_lower: pandar_connection"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/left_lower/ptp
    diag: "pandar_monitor: /sensing/lidar/left_lower: pandar_ptp"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/left_lower/temperature
    diag: "pandar_monitor: /sensing/lidar/left_lower: pandar_temperature"
    type: diag
    timeout: 5.0

  - path: /sensing/lidar/left_upper/connection
    diag: "pandar_monitor: /sensing/lidar/left_upper: pandar_connection"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/left_upper/ptp
    diag: "pandar_monitor: /sensing/lidar/left_upper: pandar_ptp"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/left_upper/temperature
    diag: "pandar_monitor: /sensing/lidar/left_upper: pandar_temperature"
    type: diag
    timeout: 5.0

  - path: /sensing/lidar/right_lower/connection
    diag: "pandar_monitor: /sensing/lidar/right_lower: pandar_connection"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/right_lower/ptp
    diag: "pandar_monitor: /sensing/lidar/right_lower: pandar_ptp"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/right_lower/temperature
    diag: "pandar_monitor: /sensing/lidar/right_lower: pandar_temperature"
    type: diag
    timeout: 5.0

  - path: /sensing/lidar/right_upper/connection
    diag: "pandar_monitor: /sensing/lidar/right_upper: pandar_connection"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/right_upper/ptp
    diag: "pandar_monitor: /sensing/lidar/right_upper: pandar_ptp"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/right_upper/temperature
    diag: "pandar_monitor: /sensing/lidar/right_upper: pandar_temperature"
    type: diag
    timeout: 5.0

  - path: /sensing/lidar/rear_lower/connection
    diag: "pandar_monitor: /sensing/lidar/rear_lower: pandar_connection"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/rear_lower/ptp
    diag: "pandar_monitor: /sensing/lidar/rear_lower: pandar_ptp"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/rear_lower/temperature
    diag: "pandar_monitor: /sensing/lidar/rear_lower: pandar_temperature"
    type: diag
    timeout: 5.0

  - path: /sensing/lidar/rear_upper/connection
    diag: "pandar_monitor: /sensing/lidar/rear_upper: pandar_connection"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/rear_upper/ptp
    diag: "pandar_monitor: /sensing/lidar/rear_upper: pandar_ptp"
    type: diag
    timeout: 5.0
  - path: /sensing/lidar/rear_upper/temperature
    diag: "pandar_monitor: /sensing/lidar/rear_upper: pandar_temperature"
    type: diag
    timeout: 5.0

  - path: /sensing/camera/0/connection
    diag: "v4l2_camera_camera0: capture_status"
    type: diag
    timeout: 1.0
  - path: /sensing/camera/1/connection
    diag: "v4l2_camera_camera1: capture_status"
    type: diag
    timeout: 1.0
  - path: /sensing/camera/2/connection
    diag: "v4l2_camera_camera2: capture_status"
    type: diag
    timeout: 1.0
  - path: /sensing/camera/3/connection
    diag: "v4l2_camera_camera3: capture_status"
    type: diag
    timeout: 1.0
  - path: /sensing/camera/4/connection
    diag: "v4l2_camera_camera4: capture_status"
    type: diag
    timeout: 1.0
  - path: /sensing/camera/5/connection
    diag: "v4l2_camera_camera5: capture_status"
    type: diag
    timeout: 1.0

  - path: /sensing/radar/front_center/connection
    diag: "topic_state_monitor_radar_front_center: radar_front_center_topic_status"
    type: diag
    timeout: 1.0
  - path: /sensing/radar/front_left/connection
    diag: "topic_state_monitor_radar_front_left: radar_front_left_topic_status"
    type: diag
    timeout: 1.0
  - path: /sensing/radar/front_right/connection
    diag: "topic_state_monitor_radar_front_right: radar_front_right_topic_status"
    type: diag
    timeout: 1.0
  - path: /sensing/radar/rear_center/connection
    diag: "topic_state_monitor_radar_rear_center: radar_rear_center_topic_status"
    type: diag
    timeout: 1.0
  - path: /sensing/radar/rear_left/connection
    diag: "topic_state_monitor_radar_rear_left: radar_rear_left_topic_status"
    type: diag
    timeout: 1.0
  - path: /sensing/radar/rear_right/connection
    diag: "topic_state_monitor_radar_rear_right: radar_rear_right_topic_status"
    type: diag
    timeout: 1.0
